travis:
  secure:
    BINSTAR_TOKEN: cOo/XjorkZ1y3YkFLry7+2kBoVjZVnkt5yBL/50BlbFhQZikLciAoz3pPHf14MB7jXxqyCPvyNxy27uIq36o9RFmp1m242TSQI7EbtEcHpzvah9K9O0KXSvTK466tiKzNuM11nhkfg5cpzNK+rCrdm5iAOPXfsOxWwd3JCwG5jk+uodYPBUCiWG8W0fumv3T/cbSjtMWsCfOxsJdWfSPbu4Azkyp+LIN/BK7/7F595DG0EFSSuIdS5IyiAKt75N9+atx5pZwUXIGZ0BX/l59shvmpl7XHmKonXvMRIA/bdN2n3ZTJUjRzuKSSFk5Gg14sXVzQmWVvZjCvLmjEAffjkwk7c4qwxaCfacWU6b9RTFIi3BRkAEK5AEErKBpOhU6GeaTnFju/yMDAqmYh2VfG+IMz8XOyRpyuw3MNWxVmseFFRS6h3R1QGO9PCBp3XfJ+M+zV48Tp9d7VP8HxuLfwF/7Ui9F3Zjqo6KL3Kw7kXMOqa2E8EccZzyBCv181wZVpTsfvK9MjHwbF4lfwbNdeWDrFDC292wk1QNsdTEuKzLd9dXyAyYLiDVXvutsuArEvvmx/eosoEVz+xxikhpdzadoVsRA7gnSkiy1xN6dXEGwAxF0/6x9qNC/U5STH0s1uWQdzbZSskhA99wbs56kElIiHEuAkJ4XRDogZTjelfk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
